name: 'Dotenv Cloud Run Action'
description: 'Get a comma-separated string of env variables for Cloud Run'
inputs:
  path:
    description: 'Path to .env file'
    default: '.env'
    required: false
  prefix:
    description: 'Prefix to filter environment variables with'
    required: false
outputs:
  dotenvstring:
    description: 'The string to use for Cloud Run --set-env-vars'
runs:
  using: 'node16'
  main: 'dist/index.js'
